-- Generated 2026-05-21 by realistic-demo-inventory-pass-2
-- Premium dealer-grade descriptions for all 65 demo listings
BEGIN;

-- 2021 Nautique G23 Wake Boat
UPDATE listings SET description = 'Tournament-spec 23'' Nautique G23 — the bench-mark surf and wake boat for competitive riders. PCM ZR450 6.2L 450hp, Nautique Surf System (NSS) with left/right tap, surf-band stereo, Linc Panoray dash and ballast plumbed to ~3,000 lbs. Approximately 280 freshwater hours, single-owner, always covered between sessions, never moored. Tower bimini, 4-way speaker bar, Polk Audio sub, trailer included. Surf-ready out of the slip — turnkey for clean, head-high waves the family will actually ride. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'aadb78fd-0522-4d6d-aabf-ba5cec40dae6';

-- 2021 Pathfinder 2600 TRS
UPDATE listings SET description = '2021 Pathfinder 2600 TRS — 26'' Gulf Coast bay boat purpose-built for redfish flats, trout grass and the inshore-to-near-shore crossover. Single Yamaha F400 4-stroke V8 (~310 hrs, factory warranty remaining), shallow 14" draft, Power-Pole Blade 10'', 36V Minn Kota Ultrex 112, Garmin 12" MFD with side- and down-scan, casting platforms fore and aft, three livewells, hardtop with rocket launchers. Stored covered on aluminum trailer. Light tackle ready. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '6c0d3866-e2f9-4ec0-b3d3-19e4d4aac184';

-- 2022 Bennington 25 QX Pontoon
UPDATE listings SET description = '2022 Bennington 25 QX tritoon — the brand''s premium luxury entertainer in a 25'' triple-tube ESP performance package. Mercury 400 Verado V10 (~95 hrs), swingback bow loungers, captain''s helm chair, JL Audio Pro M6 with subwoofer, Garmin 9" touch, bow filler cushion, premium teak SeaDek flooring, full mooring cover. Cruises in the mid-40s and pulls a slalom skier without complaint. Freshwater-only, tandem-axle trailer included. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '7402d3d0-c5e3-43bd-bacb-8c585677843f';

-- 2023 Robalo R272
UPDATE listings SET description = '2023 Robalo R272 — 27'' bay-boat crossover that fishes inside and runs offshore when it''s calm. Twin Yamaha F200 SHO, ~140 hrs, factory warranty remaining. Fiberglass T-top with electronics box, two pressurized livewells, raw-water washdown, Garmin GPSMAP 943xsv with Fantom radar pre-wire, freshwater shower, head compartment with porta-potti, two batteries on switch with ACR. Single owner, always rinsed, always covered. Family-friendly layout. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'e62dfa53-37c2-4c79-8912-e69bcf241cb1';

-- 2023 Grady-White Freedom 285
UPDATE listings SET description = '2023 Grady-White Freedom 285 — 28'' dual-console family fisher with the legendary SeaV² hull. Twin Yamaha F300 4-strokes (~165 hrs), Garmin 8612xsv at the helm, JL Audio MM100s stereo, hardtop with electronics box, full enclosure, Lewmar windlass, head compartment, two livewells, raw- and freshwater washdowns. Cruise comfortably at 32 kts, top end ~46 kts. Stored under cover lift. Bow-to-stern Grady reliability and a near-new boat at well below replacement. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'de23271b-8fb3-45bf-8310-127c65da256f';

-- 2024 Boston Whaler 330 Outrage
UPDATE listings SET description = '2024 Boston Whaler 330 Outrage — 33'' unsinkable, all-conditions center console outfitted for offshore fishing and family cruising. Triple Mercury 300 Verado V8s (~85 hrs), Seakeeper-ready, Garmin twin 16" displays with autopilot and Fantom radar, premium hardtop with bolster seating, Eskimo ice maker, enclosed head with shower, summer kitchen, sea chest plumbing. Cruise 32-35 kts, range ~340 nm. Single owner, dealer maintained, full transferable Whaler warranty. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '2be80eb4-c56b-4327-b949-e0d77d0a3c7e';

-- 2020 Nor-Tech 390 Sport
UPDATE listings SET description = '2020 Nor-Tech 390 Sport — 39'' Florida-built stepped-V offshore performance center console. Quad Mercury Racing 400R outboards (~210 hrs), digital throttle/shift, hydraulic jackplates, color-matched gel, Livorsi gauges, JL Audio with twin 12" subs, billet hardtop, full bolster seating, head compartment. GPS-verified 95+ mph. Trailered, always covered, professionally rigged. Built for the run to Bimini and back the same afternoon. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '7d9925fa-0e9c-4182-ba07-77964e8754fb';

-- 2021 Cigarette 42X
UPDATE listings SET description = '2021 Cigarette 42X — flagship Cigarette Racing center console, hand-laid carbon-fiber stringer grid and deck, Mercury Racing 450R quads (~140 hrs) on Mercury Joystick Piloting. SeaKeeper 6, JL Audio M6, twin Garmin 16", custom interior by Cigarette Performance, dive-door, integrated grill, freshwater shower. Verified 130+ mph two-up. The collector-grade poker-run boat — delivered with full warranty paperwork and known service history. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'fd0725e7-6528-402d-9085-b6e4a507c9af';

-- 2022 Fountain 38SC
UPDATE listings SET description = '2022 Fountain 38SC — 38'' sport-center console with the classic Fountain offshore race hull. Triple Mercury Racing 400R (~175 hrs), Mercury VesselView linked to Garmin 12" MFD, JL Audio M-series stereo, head compartment, color-matched hull and topsides, fiberglass hardtop with electronics box and rocket launchers. Cruise 60+ mph, top end ~80 mph. Tournament-spec rigging, dock-line ready. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'deed0c73-80ec-418e-ad29-8382654a4442';

-- 2023 Scarab 255 Open
UPDATE listings SET description = '2023 Scarab 255 Open — 25'' jet-drive performance bowrider, Rotax 1630 ACE twin 300hp jet pack (~120 hrs), iBR forward/neutral/reverse, surf gate package, wakeboard tower with Bimini and four tower speakers, JL Audio premium with sub, Garmin 7" touch, snap-in marine carpet. Beachable, family-friendly, runs in skinny water others can''t touch. Trailer included. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '19b8d1df-a2e8-4c5a-a5e2-588829270481';

-- 2020 Tiara 48 LS
UPDATE listings SET description = '2020 Tiara 48 LS — 48'' express-cruising luxury sport coupe with Volvo IPS 600 joystick docking, ~480 engine hours. Two-stateroom layout with full beam master, galley-up, retractable hardtop, hydraulic swim platform, Seakeeper 9, Side-Power bow and stern thrusters, full Garmin glass bridge. Tiara craftsmanship throughout with teak-and-holly soles, granite counters, and CNC-fit joinery. Single owner, Tiara-dealer maintained from new. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '347d7496-2bbb-47cf-9bb0-33bc0213e358';

-- 2020 Azimut 55 Flybridge
UPDATE listings SET description = '2020 Azimut 55 Flybridge — Italian flybridge motoryacht with three staterooms, three heads and crew quarters. Twin Volvo Penta IPS 800 (~620 hrs), Seakeeper 9, joystick docking, Garmin twin 16" glass cockpit, hydraulic swim platform, Besenzoni gangway, full air conditioning, full cockpit and flybridge enclosures, watermaker. Mediterranean styling, Lewis-Hamilton-stage finishes. Owner''s manual, complete maintenance records, dealer survey on file. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '884b87c7-def0-47f3-9fd1-1d3682ff09e2';

-- 2021 Viking 54 Convertible
UPDATE listings SET description = '2021 Viking 54 Convertible — 54'' tournament sportfisherman with twin Caterpillar C18 ACERT diesels (~720 hrs), Seakeeper 16, Palm Beach tower with Pipewelders outriggers, mezzanine seating with bait freezers, three-stateroom layout. Full 2023 refit: new electronics suite (Furuno TZT2 with NavNet radar/sonar), bottom paint, varnish, soft goods. Tournament fished, captain-maintained. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'ac87fc27-5b6a-4f67-9b21-7f7f35ea36c0';

-- 2022 Sea Ray Sundancer 370
UPDATE listings SET description = '2022 Sea Ray Sundancer 370 — 37'' express cruiser with twin Mercury Bravo Three 350hp sterndrives (~210 hrs), full galley, two-cabin layout with mid-stateroom, enclosed head with separate shower, bow thruster, hydraulic swim platform, Raymarine Axiom 12 MFD, JL Audio premium. Cockpit grill, refrigerator and ice maker. Always slipped, full canvas and gel coat preserved. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'a999565c-6eb9-47e7-b853-6161525f06c8';

-- 2022 Prestige 520 Flybridge
UPDATE listings SET description = '2022 Prestige 520 Flybridge — 52'' three-cabin French flybridge with twin Volvo IPS 600 (~430 hrs) and joystick docking. Hydraulic swim platform, full galley-up with cockpit access, two-zone Cruisair, bow thruster, Garmin twin 16" displays, FLIR thermal camera, Seakeeper 9. Cherrywood interior, en-suite master amidships. Owner-upgraded with watermaker and electric grill. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'f8d42858-2828-42c2-8f88-343569188a34';

-- 2022 Sea Ray Sundancer 370
UPDATE listings SET description = '2022 Sea Ray Sundancer 370 — 37'' Sundancer in showroom condition, just over 120 hours on the twin Mercury Bravo Three 350 sterndrives. Two-cabin layout, head with separate shower stall, full galley with cooktop and refrigerator, Raymarine Axiom electronics, bow thruster, hydraulic swim platform, full canvas. Gulf-coast freshwater rinsed and covered when not in use. Demonstrator-grade. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'eca8184e-b64c-46ac-8b41-eeb9f9a52f23';

-- 2024 Azimut 53 Flybridge
UPDATE listings SET description = '2024 Azimut 53 Flybridge — current-generation Azimut Flybridge with under 120 hours on twin Volvo IPS 800. Three-cabin, three-head layout, full beam owner''s stateroom amidships, galley-up plan, Besenzoni gangway, hydraulic swim platform, Seakeeper 9, joystick docking. Garmin OneHelm glass bridge, full air, watermaker, satellite TV. Balance of factory warranty transfers. Italian yachting at the cutting edge — true turnkey delivery. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '45922b7b-138c-4c68-b8c2-e890ff2aeac9';

-- 2019 Everglades 355T
UPDATE listings SET description = '2019 Everglades 355T — 35'' RAMCAP-foam-cored center console, triple Yamaha F300 (~640 hrs), Garmin 12" twin display, hardtop with full electronics box, Seakeeper 5 ready, two pressurized livewells, freshwater shower, head compartment with porta-potti. Full canvas, taco outriggers, professionally maintained by authorized Everglades dealer. Outstanding offshore ride. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'd6bc3324-34ed-4aa6-8db2-a111b6a4473a';

-- 2020 Yellowfin 36 Offshore
UPDATE listings SET description = '2020 Yellowfin 36 Offshore — tournament-grade 36'' Yellowfin with triple Yamaha F300 4-strokes (~520 hrs), Garmin 16" twin glass bridge, autopilot, Fantom radar, Airmar B175 1kW transducer. Reelax outriggers, tower with full controls, Eskimo ice chipper, dive door, freshwater wash. SeaKeeper 5 installed. Built for real tournament-day deployments. Captain maintained. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '3ae90a76-e26b-41b9-ab21-12e402e03287';

-- 2021 Mako 414 CC
UPDATE listings SET description = '2021 Mako 414 CC — 41'' offshore center console, quad Yamaha F300 (~380 hrs), 220-gallon fuel for legitimate canyon range. Garmin 16" twin displays with Fantom radar and autopilot, three pressurized livewells, hardtop with bolster seating, enclosed head, freshwater shower, JL Audio. Heavy-glass offshore hull with the kind of buyback resale Mako has earned. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'a4b7129b-4dca-4330-b67a-a97500d4d4cf';

-- 2021 Regulator 41
UPDATE listings SET description = '2021 Regulator 41 — flagship 41'' Regulator center console, twin/triple Yamaha F350 (verify configuration in survey, ~410 hrs), full Palm Beach tower with second helm, taco outriggers, Garmin 22" twin glass bridge, autopilot, Fantom radar, Eskimo ice chipper, two pressurized livewells, dive door, enclosed head with shower. Captain owned and tournament campaigned. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'c053eca6-91fe-4f19-b978-c5c6d2fc61f3';

-- 2021 Cobia 350 CC
UPDATE listings SET description = '2021 Cobia 350 CC — 35'' family-friendly bluewater center console, twin Yamaha F350 (~310 hrs), Garmin 12" twin display, hardtop with electronics box, outriggers, two pressurized livewells, enclosed head with porta-potti, freshwater shower, JL Audio with bow sub. Single owner, dealer maintained, full canvas. Comfortable in 3-4'' offshore chop. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'ebd7a997-c607-43c6-a956-89852d432741';

-- 2022 Boston Whaler 380 Outrage
UPDATE listings SET description = '2022 Boston Whaler 380 Outrage — flagship 38'' Outrage, Mercury 400 Verado V10 triples (~240 hrs), Seakeeper 6 gyro stabilizer, twin Garmin 22" glass bridge, autopilot, Fantom radar, summer kitchen with Eskimo ice maker and grill, enclosed head with shower, premium hardtop with bolster seating. Unsinkable Whaler hull with offshore tournament rigging. Whaler-dealer maintained from new. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '19a4c9dc-8d0b-436e-9139-da8a1761ed26';

-- 2022 Robalo R360
UPDATE listings SET description = '2022 Robalo R360 — 36'' center console finished in Robalo blue with bone interior. Twin Yamaha F300 4-strokes (~210 hrs), hardtop with full electronics box, Garmin 12" twin MFDs, bow thruster, two pressurized livewells, freshwater shower, JL Audio with sub. Freshwater-use only, stored under cover lift since new. Looks and runs like new. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'eaf77f99-ccb0-431f-a581-64e339c6ed68';

-- 2023 Grady-White Canyon 376
UPDATE listings SET description = '2023 Grady-White Canyon 376 — 37'' Canyon Series, triple Yamaha F350 (~180 hrs), Simrad NSO evo3S triple 16" multifunction displays, Halo24 radar, autopilot, summer kitchen, enclosed head with shower, hardtop with electronics box, outriggers, two pressurized livewells. The Grady SeaV² hull with the best offshore ride in class. Dealer maintained with factory warranty remaining. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '6c47bea5-28a2-4f1d-acff-877ba939694e';

-- 2023 Sportsman Heritage 351
UPDATE listings SET description = '2023 Sportsman Heritage 351 — 35'' family-friendly luxury bluewater console, triple Mercury 300 Verado V8 (~140 hrs), full balance of Mercury warranty. Garmin 12" twin glass bridge, hardtop with electronics box, two pressurized livewells, freshwater shower, enclosed head, premium SeaDek throughout, JL Audio with subwoofer. Dealer-maintained, single owner. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '98f8ac72-fffd-4f60-aab0-5f39e9b857d1';

-- 2023 Pursuit S 428 Sport
UPDATE listings SET description = '2023 Pursuit S 428 Sport — 42'' luxury sport center console, quad Yamaha XTO 425s (~155 hrs), Seakeeper 6 gyro, twin Garmin 22" displays with autopilot and Fantom radar, premium hardtop with bolster seating, enclosed head with separate shower, Eskimo ice maker, summer kitchen, Webasto diesel heater. Mid-cabin layout with queen island berth — overnight comfort with offshore capability. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '2235b6c9-ab8d-46d8-9572-ef5fe4ffb4d4';

-- 2022 BMW M4 Competition
UPDATE listings SET description = '2022 BMW M4 Competition xDrive — Twin-turbo S58 3.0L inline-six, 503hp/479 lb-ft, 8-speed M Steptronic, all-wheel drive with M xDrive, M Active differential. Approximately 18,400 mi, single owner, dealer-serviced. Carbon-fiber roof, M Carbon exterior package, M Drive Professional, head-up display, Harman Kardon, 20" 826M forged. Originally optioned at $89k+. Clean Carfax, no stories. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '2386f82f-36f1-4894-9e51-fe874319d3a0';

-- 2023 Subaru Outback Wilderness
UPDATE listings SET description = '2023 Subaru Outback Wilderness — 2.4L turbocharged boxer, 260hp/277 lb-ft, CVT with X-MODE dual-function (Snow/Dirt + Deep Snow/Mud) and full-time Symmetrical AWD. 9.5" ground clearance, Yokohama Geolandar AT tires, anti-glare matte black hood, integrated roof rails with 700-lb static capacity. ~24,800 mi, EyeSight driver assistance, Harman Kardon premium, leatherette with copper stitching. Pacific Northwest single owner. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '05589a1c-2c2d-468a-921b-4475fe1aac54';

-- 2023 Mercedes-Benz C300 4MATIC
UPDATE listings SET description = '2023 Mercedes-Benz C300 4MATIC — current-generation W206 chassis with 2.0L turbo I4 mild-hybrid, 255hp/295 lb-ft, 9G-TRONIC, 4MATIC all-wheel drive. Approximately 16,200 mi. Premium Package (Burmester 3D, Memory, Heated Front, 11.9" portrait MBUX), AMG Line exterior, 19" multi-spoke, panoramic roof. Selenite Grey over black MB-Tex. CPO-eligible, dealer-serviced, clean Carfax. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '697d7827-4c59-4c44-bbdc-bfc135027fca';

-- 2024 Honda Accord Sport
UPDATE listings SET description = '2024 Honda Accord Sport (11th-gen) — 1.5L turbocharged inline-4, 192hp/192 lb-ft, CVT, FWD. ~14,800 mi, one owner, full Honda service. Sport trim adds 19" black alloys, dual exhaust, sport-tuned suspension, black mesh grille. Honda Sensing (adaptive cruise, collision mitigation braking, road departure mitigation, lane keep assist), wireless Apple CarPlay / Android Auto, 10.2" digital cluster. Clean title. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '6ba9a6f7-5a97-4ad8-bc4d-2ce3333efd8c';

-- 2024 Toyota Camry XSE
UPDATE listings SET description = '2024 Toyota Camry XSE Hybrid — 2.5L Atkinson-cycle 4-cyl + electric motor, combined 225hp, eCVT, FWD. ~16,500 mi. XSE-exclusive sport-tuned suspension, 19" machined alloys, two-tone midnight roof, paddle shifters. JBL 9-speaker premium audio, wireless CarPlay/Android Auto, leather-trimmed sport seats, heated front seats, Toyota Safety Sense 3.0. Combined ~46 mpg. Single owner. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '568614f8-e436-41e6-83bf-97a0f412583d';

-- 2024 Kia Telluride SX Prestige
UPDATE listings SET description = '2024 Kia Telluride SX — 3.8L V6, 291hp/262 lb-ft, 8-speed automatic, AWD with lock mode. ~13,200 mi, second-row captain''s chairs, three-row seven-passenger. Highway Driving Assist 2 (lane-centering, automatic lane-change assist), Harman Kardon premium audio, panoramic 12.3" curved dual display, Nappa leather, heated/ventilated front and second-row, head-up display. Top-trim SX with factory tow package. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '995f9d8b-7c04-4711-a6aa-00a252461e8c';

-- 2024 Mazda CX-5 Turbo
UPDATE listings SET description = '2024 Mazda CX-5 Turbo Premium — 2.5L turbocharged Skyactiv-G, 256hp/320 lb-ft on 93 octane, 6-speed automatic, i-Activ AWD. ~12,600 mi, one owner. Nappa leather, 10-speaker Bose, 10.25" display, head-up display, ventilated front seats, wireless CarPlay/Android Auto, 19" alloys. Mazda CPO eligible. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '2fabf458-a490-4af5-bdb5-5b76e6e8093c';

-- 2024 Hyundai Tucson Limited
UPDATE listings SET description = '2024 Hyundai Tucson Limited Hybrid — 1.6L turbo + electric, 226hp combined, 6-speed automatic, HTRAC AWD. ~11,400 mi, panoramic sunroof, BlueLink connected services, Highway Driving Assist 2 with lane-centering. Heated and ventilated front seats, heated rear seats, 8-speaker Bose, dual 10.25" curved display, Nappa leather. Hybrid economy with full Limited content. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '20b05173-d1e7-45d0-9235-bfc26afc4160';

-- 2023 Toyota Tundra TRD Pro
UPDATE listings SET description = '2023 Toyota Tundra TRD Pro CrewMax — i-FORCE MAX hybrid powertrain (3.4L twin-turbo V6 + e-motor), 437hp/583 lb-ft, 10-speed auto, full-time 4WD with electronic locking rear differential and TRD off-road tuned suspension. ~22,800 mi, single owner. FOX QS3 internal-bypass shocks, 1.1" front lift, TRD Pro 18" forged BBS-style wheels, Falken Wildpeak A/T, skid plates, multi-terrain monitor, Premium 14" touchscreen, JBL 12-speaker, panoramic camera. Lunar Rock over heated/ventilated red-stitched leather. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '7e4a30b6-0d46-4b69-a035-3530c5ecaeb6';

-- 2023 Toyota Tacoma TRD Pro
UPDATE listings SET description = '2023 Toyota Tacoma TRD Pro Double Cab — 3.5L V6, 278hp/265 lb-ft, 6-speed automatic, part-time 4WD with electronic locking rear, Crawl Control + Multi-Terrain Select. ~28,500 mi. FOX 2.5" internal-bypass shocks, 1" front lift, TRD Pro 16" wheels with all-terrain Goodyear Wrangler, JBL premium 7-speaker, 8" touchscreen, sunroof. Lunar Rock paint. Maintained at Toyota dealer. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '4abca147-27f9-47f5-a3bc-05fe818cb8a6';

-- 2024 Ford F-150 Lightning Platinum
UPDATE listings SET description = '2024 Ford F-150 Lightning Lariat Extended Range — dual electric motors, 580hp/775 lb-ft, 131 kWh extended-range battery, ~320 mi EPA range, 10,000-lb tow (max trailer-tow package). ~9,800 mi, BlueCruise 1.2 hands-free highway driving, Pro Power Onboard 9.6 kW, Ford Co-Pilot 360 Assist 2.0, panoramic vista roof, B&O Unleashed audio. 22-inch six-spoke machined aluminum. Star White Metallic. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '078b3097-9cd3-4bfa-a899-f9655b97e5ed';

-- 2024 Ford F-350 Platinum
UPDATE listings SET description = '2024 Ford F-350 Super Duty Platinum Crew Cab Long Bed 4x4 — 6.7L Power Stroke V8 turbo-diesel, 500hp/1,200 lb-ft, 10-speed TorqShift HD, electronic-locking rear axle. ~14,200 mi, single owner. 5th-wheel/gooseneck prep, max tow package (~37,000 lb conventional), Platinum content: Nirvana leather with 24-way Multi-Contour seats, B&O 18-speaker, 12" SYNC 4 with navigation, panoramic vista roof. Truck of the Year-grade fit and finish, factory-warrantied diesel. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '5fd1e9f7-d97f-43dc-9839-ebdfd351ff7f';

-- 2023 Porsche 911 GT3 RS
UPDATE listings SET description = '2023 Porsche 911 GT3 RS (992.1) — 4.0L naturally-aspirated flat-six, 518hp at 8,500 rpm, 7-speed PDK, RWD. ~2,400 mi. Active aerodynamics with DRS, adjustable wing & diffuser, center-lock magnesium wheels, ceramic composite brakes. Weissach package (carbon roof, carbon ARB, magnesium wheels), full PPF, Clubsport package with bolted half-cage and 6-point harness, lightweight bucket seats. GT-Silver over black Race-Tex. The road-going Cup car. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'cedf028a-ed3c-4a39-8d87-476667f0c376';

-- 2023 Mercedes-AMG GT 63 S
UPDATE listings SET description = '2023 Mercedes-AMG GT 63 S 4-Door Coupe — handcrafted 4.0L AMG biturbo V8, 630hp/664 lb-ft, AMG SPEEDSHIFT MCT 9G, AMG Performance 4MATIC+, rear-axle steering. ~8,900 mi. AMG Carbon Ceramic brakes, AMG DYNAMIC PLUS pack (Drift Mode, AMG engine mounts), Performance exhaust, Carbon Fiber Trim Pack II, Burmester High-End 3D, panoramic roof, Nappa leather. Selenite Grey Magno over black/red. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'c6826590-6606-48e8-a87b-0859325e5049';

-- 2024 BMW M4 Competition xDrive
UPDATE listings SET description = '2024 BMW M4 Competition Coupe — S58 3.0L twin-turbo inline-six, 503hp/479 lb-ft, 8-speed M Steptronic, RWD with M Active differential. ~5,200 mi. M Carbon bucket seats (track-rated, weight-saving), Carbon Exterior Package, Carbon Roof, M Performance exhaust (factory), M Drive Professional with M Drift Analyzer, full PPF wrap. Brooklyn Grey over Yas Marina Blue/black Merino. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '0d648a98-90ee-4798-8bc6-c88f5791c047';

-- 2024 Audi RS 5 Sportback
UPDATE listings SET description = '2024 Audi RS 5 Sportback — 2.9L twin-turbo V6, 444hp/443 lb-ft, 8-speed Tiptronic, quattro AWD with sport differential. ~7,800 mi. RS Dynamic Plus (carbon ceramic brakes, dynamic steering, 180 mph derestrict), Bang & Olufsen 3D, Virtual Cockpit Plus, head-up display, Nappa Honeycomb sport seats, full carbon trim, 20" forged. Nardo Grey over black. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '6580858f-8336-4ba6-b83d-7195130ccdc3';

-- 2024 Chevrolet Corvette Z06
UPDATE listings SET description = '2024 Chevrolet Corvette Z06 3LZ — naturally-aspirated 5.5L LT6 flat-plane crank V8, 670hp at 8,400 rpm/460 lb-ft, 8-speed dual-clutch, MR4 magnetorheological. ~4,100 mi. Z07 Performance Package (carbon ceramic brakes, carbon aero kit, Michelin Cup 2 R), carbon-fiber wheels, full-length carbon hood vent, GT2 carbon bucket seats, 14-speaker Bose. Sea Wolf Gray over Adrenaline Red. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '9ac879b3-be79-473b-b6bc-33ccb1777b6a';

-- 2024 Lamborghini Huracan STO
UPDATE listings SET description = '2024 Lamborghini Huracán STO — naturally-aspirated 5.2L V10, 631hp/417 lb-ft, 7-speed dual-clutch LDF, RWD. Only ~210 mi from new. Carbon-fiber clamshell front (cofango), magnesium wheels, CCM-R carbon-ceramic brakes, Bridgestone Potenza Sport (road) and Pirelli Trofeo R (track). Alcantara cabin with carbon shell racing seats, 4-point harnesses, carbon roll bar. Bianco Asopo over Nero Cosmus / Rosso Mars. Race-bred road car, near-zero-mile collector example. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '9460b3cc-b12e-46e7-8650-8432d7e6bd11';

-- 2024 Porsche 911 GT3 RS
UPDATE listings SET description = '2024 Porsche 911 GT3 RS (992.1) — 4.0L naturally aspirated flat-six, 518hp at 8,500 rpm/342 lb-ft, 7-speed PDK, RWD. ~1,800 mi from new. Weissach Package (carbon roof, carbon front and rear ARBs, magnesium wheels), full PPF, GT-Silver Metallic over black Race-Tex with carbon weave. Front-axle lift, ceramic composite brakes, lightweight Clubsport buckets. Loaner-friendly, full Porsche history. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'c09f4f16-0cfc-45b1-b317-ed751c1d9047';

-- 1967 Ford Mustang GT Fastback
UPDATE listings SET description = '1967 Ford Mustang GT Fastback — Highland Green over Parchment, 390 FE big-block V8 (4V), Toploader 4-speed manual, 9" rear with 3.50:1 Traction-Lok. Frame-off rotisserie restoration with concours-correct sheet metal, Marti Report on file. Power front discs, factory styled steel wheels with hubcaps and trim rings, GT-equipment-group fog lamps, GT exhaust trumpets. Numbers-matching driveline. Investment-grade S-code GT fastback — Bullitt-spec icon. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '01d6ff78-2648-48c1-9eee-928fdd6ef936';

-- 1969 Chevrolet Camaro Z/28
UPDATE listings SET description = '1969 Chevrolet Camaro Z/28 — original DZ 302 small-block (11.0:1, solid-lifter), Muncie M21 close-ratio 4-speed, 12-bolt Posi 3.73. Numbers-matching block, heads, transmission. Lemans Blue with black hockey-stripe rally pack and cowl induction hood. Documented build sheet, restoration photos, NCRS-style judging level. Power front discs, period-correct Goodyear Polyglas redlines. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '4c447df3-e30c-4c46-9e3d-b4ce07af9bfe';

-- 1970 Chevrolet Chevelle SS 454
UPDATE listings SET description = '1970 Chevrolet Chevelle SS 454 LS6 — the apex year and the apex engine. Solid-lifter 454 LS6 (factory-rated 450hp, gross), Muncie M22 "Rock Crusher" close-ratio 4-speed, 12-bolt Posi 4.10. Cranberry Red over black bucket interior, cowl-induction hood, SS5 wheels with Polyglas redlines. Frame-off rotisserie, documented, build-sheet and Protect-O-Plate on file. Numbers-matching driveline. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '11159b20-1777-4692-87cd-78284a6d7d44';

-- 1972 Pontiac GTO Judge
UPDATE listings SET description = '1972 Pontiac GTO ''The Judge'' — 455 HO V8 with Ram Air IV-style induction, Muncie M22 4-speed, 3.55 Safe-T-Track. Original numbers-matching block (PHS documentation), Carousel Red with classic Judge graphics and rear spoiler, Rally II wheels, Goodyear Polyglas. Frame-off concours-quality restoration with factory-correct Endura nose, hood scoop, hood tach. Final-year Judge — among the rarest of muscle-era halo cars. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'cf4cfe89-1ae6-45cd-8320-cab1f10e8a0c';

-- 1975 Piper Cherokee Six 300
UPDATE listings SET description = '1975 Piper PA-32-300 Cherokee Six — six-place utility workhorse. Lycoming IO-540 300hp, approx. 4,200 TT airframe, ~720 SMOH (mid-time, Lycoming reman). Garmin GTN 650 GPS/Nav/Com WAAS, GTX 345 ADS-B In/Out, KAP 140 two-axis autopilot, JPI EDM-700 engine monitor. Clamshell rear door, cargo configuration. Fresh annual 12/2025, no damage history per logs, hangared. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'e01e3a3d-33ed-4c19-a80d-253bbb8415d4';

-- 2015 Cessna 182T Skylane
UPDATE listings SET description = '2015 Cessna 182T Skylane — Lycoming IO-540-AB1A5 230hp, approx. 1,650 TT airframe/engine. Garmin G1000 NXi with GFC700 autopilot, ADS-B In/Out via GTX 345R, SVT synthetic vision, FlightStream 510. Leather, air conditioning, hangared since new. Fresh annual 03/2026, complete and continuous logs from delivery, no damage history. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '957c411a-6189-476d-8162-2ad7e02c7ad5';

-- 2018 Cirrus SR22T G6
UPDATE listings SET description = '2018 Cirrus SR22T G6 — turbo-normalized Continental TSIO-550-K 315hp, approx. 920 TT airframe/engine, ~410 hrs since major. Perspective+ avionics by Garmin, GFC700 autopilot, full TKS Flight Into Known Icing (FIKI), CAPS parachute (repack due 2028 per current spec), air conditioning, premium leather, oxygen. Hangared since new, fresh annual 02/2026, complete logs, no damage. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'c63746c4-d766-45c9-b705-95ed54c44009';

-- 2020 Diamond DA40 NG
UPDATE listings SET description = '2020 Diamond DA40 NG — jet-A diesel Austro AE300 168hp, approx. 480 TT airframe/engine. Garmin G1000 NXi, GFC700 autopilot, FIKI-ready airframe (de-ice STC installed), leather interior. Composite airframe with low total time and excellent economy. Fresh annual 01/2026, complete logs, no damage history, hangared. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'bbf6921f-e1b3-41a8-85fb-403caecf2df3';

-- 1978 Cessna 310R
UPDATE listings SET description = '1978 Cessna 310R — classic light twin. Twin Continental IO-520-MB 285hp, approx. 6,800 TT airframe, ~720/740 SMOH (mid-time). Aspen Evolution E5 primary flight display, Garmin GTN 650 WAAS, GTX 345 ADS-B In/Out, S-TEC 55X autopilot. Long-range tip tanks, club seating, fresh annual 04/2026. Complete logs, documented damage history reviewed and repaired to factory spec. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '2ad62844-5e97-4fd6-a322-fb09eb71f3f7';

-- 2008 Piper Seneca V
UPDATE listings SET description = '2008 Piper Seneca V — twin-turbocharged Continental TSIO-360-RB, 220hp each, approx. 2,100 TT airframe, ~580/610 SMOH. Garmin G1000 with GFC700 autopilot, ADS-B In/Out, A/C, six-place club seating, oxygen, weather radar. Fresh annual 11/2025, complete continuous logs from new, no damage history. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'baf6e8af-6f43-4b47-8eea-a1ac8b0bc159';

-- 2019 Beechcraft Baron G58
UPDATE listings SET description = '2019 Beechcraft Baron G58 — twin Continental IO-550-C 300hp each, approx. 980 TT airframe/engines. Garmin G1000 NXi with dual GTC touchscreen controllers, GFC700 autopilot, FIKI, A/C, Tanis preheat. Six-place cabin-class twin with full Garmin glass and excellent dispatch reliability. Hangared, fresh annual 03/2026, complete continuous logs, no damage. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '21bb2284-d34c-4b37-bbca-c81a19392fb7';

-- 2012 King Air 350i
UPDATE listings SET description = '2012 Beechcraft King Air 350i — twin PT6A-60A turboprops 1,050 shp each, approx. 3,800 TT airframe, ~1,650/1,720 SHSI engines (on Pratt-and-Whitney ESP program where applicable). Pro Line 21 with IFIS, dual FMS-3000, Collins TCAS-4000, TAWS-B, RVSM-certified. Executive 9-place interior with refreshment center, lavatory aft, satellite phone, dual-zone climate. Fresh Phase 1-4 inspection 12/2025, complete logs since new. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '82a9a197-eb2b-4649-8774-6731a6ab219f';

-- 2016 Pilatus PC-12 NG
UPDATE listings SET description = '2016 Pilatus PC-12 NG — single Pratt & Whitney PT6A-67P 1,200 shp, approx. 1,900 TT airframe/engine. Honeywell Apex avionics, full glass with synthetic vision, autothrottle, RVSM, ADS-B Out, FANS-1/A. Executive 6+1 interior with lavatory and refreshment center, ample baggage compartment, large cargo door. Hangared, fresh Phase A-D 04/2026, complete continuous logs, no damage history. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '190a66be-14f7-45da-894b-b054fad1a102';

-- 2020 Daher TBM 940
UPDATE listings SET description = '2020 Daher TBM 940 — Pratt & Whitney PT6A-66D 850 shp, approx. 720 TT airframe/engine. Garmin G3000 with HomeSafe Autoland emergency autoland, autothrottle, synthetic vision, FIKI, four-blade Hartzell composite prop. Six-seat executive interior, club seating, factory air. Hangared since new, fresh annual 02/2026, complete continuous logs, no damage. Top-of-the-line single-engine turboprop. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'a3ef8d2d-5cad-49ee-8ea7-410b7c57481a';

-- 2015 Embraer Phenom 300
UPDATE listings SET description = '2015 Embraer Phenom 300 — twin Pratt & Whitney PW535E turbofans, approx. 2,800 TT airframe, ~1,400/1,420 cycles. Garmin Prodigy Touch (G3000 base) avionics, ADS-B Out, FANS-1/A, RVSM, autothrottle, synthetic vision. Executive 7-seat club configuration with aft lavatory, Gogo factory wifi, dual-zone climate, external baggage. Fresh 600-hour 10/2025, complete continuous logs since new. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '3f747ce3-1596-48f8-bd65-92d07c83fbc0';

-- 2019 Cessna Citation CJ4
UPDATE listings SET description = '2019 Cessna Citation CJ4 — twin Williams FJ44-4A turbofans, approx. 1,650 TT airframe, ~720 cycles. Collins Pro Line 21 with dual FMS-3000, dual IRS, TCAS-II 7.1, EGPWS, RVSM, ADS-B Out, FANS-1/A. Executive 8-seat double-club with aft lavatory, ATG-5000 Gogo wifi, refreshment center, external baggage. Fresh Doc 1-12 inspection 03/2026, complete continuous logs, no damage. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'f5e1e5af-7211-445a-bea9-5e29389eacfb';

-- 2017 Robinson R66 Turbine
UPDATE listings SET description = '2017 Robinson R66 Turbine — Rolls-Royce RR300 270 shp, approx. 980 TT airframe/engine. Aspen Evolution PFD/MFD, Garmin GTN 650 WAAS, GTX 345 ADS-B In/Out, leather, A/C, ground-handling wheels. Hangared since new, fresh 100-hour/annual 01/2026, complete continuous logs, no damage history. Capable five-place turbine helicopter. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '72cf6b9f-a3d6-4303-a0b7-41b393e53ab7';

-- 1944 North American T-6 Texan
UPDATE listings SET description = '1944 North American AT-6D Texan — WWII Allied advanced trainer, ground-up restoration with documented airframe and engine logs. Pratt & Whitney R-1340-AN-1 600hp radial, approx. 4,800 TT airframe (life-of-airframe verification on file), ~480 SMOH on radial, fresh annual 09/2025. Period instrument panel, military paint scheme, smoke system, airshow-ready. Hangared. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = 'c67d280c-eb15-48be-89b8-15da1b79540d';

-- 2021 Icon A5
UPDATE listings SET description = '2021 ICON A5 — light-sport amphibious. Rotax 912iS 100hp, approx. 380 TT airframe/engine. Garmin G3X Touch, ADS-B In/Out, BRS-5 whole-airframe parachute, folding wings (trailerable behind a half-ton). Spin-resistant airframe, angle-of-attack indicator, sport-pilot eligible. Hangared, fresh annual 03/2026, complete continuous logs from new, no damage history. Aviation safety disclaimer: total times, cycles, and inspection status are estimated for demo purposes — verify all logbook entries, AD compliance, and prebuy via your A&P/IA before any transaction. [Demo listing — representative inventory for marketplace preview.]', updated_at = NOW() WHERE id = '300e7f1e-45eb-4c58-8d52-49e4e48a0fdd';

COMMIT;